# Version: 'v1.0'
# Date: '20220904'

General:
    comment: 
    seed: 2022
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: '5'    #[5]
    epochs: &epoch 100
    grad_acc: 2
    frozen_bn: False
    patience: 10
    # 需要改动的参数
    dataset_name: gbm_data # brca_data lusc_data gbm_data
    output_path: output_202212/DeepAttnMISL/  # 输出的根目录
    loss_name: CoxLoss   # CELoss CE+Loss CoxLoss Cox+Loss CoxRankingLoss
    modelname: DeepAttnMISL  # TransMIL,DeepAttnMISL,BDOOCX
    n_classes: 1 # 划分区间=输出类别  选择CoxLoss、Cox+Lossd时，这里设为1，否则为4
    nfold: 4 # 四折交叉验证

    BDOCOX:
        patches_path: patch_to_png
        cluster_num: 5
        bag_num: 20

    DeepAttnMISL:
        cluster_num: 6

Data:
    # 需要改动的参数，可选
    data_shuffle: True
    dataset_name: gbm_data  # brca_data lusc_data gbm_data

    train_dataloader:
        batch_size: 16
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

# 需要改动的参数，可选
Optimizer:
    opt: lookahead_radam
    # opt: sgd
    lr: 0.001
    opt_eps: null 
    opt_betas: null
    momentum: null 
    # momentum: 0.9
    weight_decay: 0.0002
    # weight_decay: 0.2

# Loss:
#     base_loss: CE+Loss

